# Generated by Django 4.0.3 on 2022-04-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryDB',
        ),
    ]
