# Generated by Django 4.0.3 on 2022-04-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_rename_gallery_gallerydb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerydb',
            options={'verbose_name': 'Картинка(у)', 'verbose_name_plural': 'Картинки(ок)'},
        ),
        migrations.RenameField(
            model_name='gallerydb',
            old_name='image',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='categorydb',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_category', to='shopping.gallerydb', verbose_name='Фото категории'),
        ),
    ]
