# Generated by Django 4.0.3 on 2022-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_gallerydb_options_rename_image_gallerydb_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandNameDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Производитель')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL производителя')),
            ],
            options={
                'verbose_name': 'Производитель(я)',
                'verbose_name_plural': 'Производители(ей)',
                'ordering': ('title',),
            },
        ),
    ]
