# Generated by Django 4.0.3 on 2022-04-03 11:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_brandnamedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название отзыва')),
                ('description', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('date_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отзыва')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв(а)',
                'verbose_name_plural': 'Отзывы(ов)',
                'ordering': ('-date_at',),
            },
        ),
        migrations.CreateModel(
            name='GoodsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('price', models.IntegerField(default=0, verbose_name='Цена товара')),
                ('presence', models.BooleanField(default=True, verbose_name='Наличие в магазине')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('date_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('n_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL товара')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_good', to='shopping.brandnamedb', verbose_name='Производитель')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_good', to='shopping.categorydb', verbose_name='Категория товара')),
                ('photos', models.ManyToManyField(blank=True, related_name='photos_goods', to='shopping.gallerydb', verbose_name='Фото товара')),
                ('reviews', models.ManyToManyField(blank=True, related_name='reviews_for_good', to='shopping.reviewsdb', verbose_name='Отзывы на товар')),
            ],
            options={
                'verbose_name': 'Товар(а)',
                'verbose_name_plural': 'Товары(ов)',
                'ordering': ('-date_at',),
            },
        ),
    ]
