# Generated by Django 4.0.3 on 2022-04-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_remove_goodsdb_reviews_reviewsdb_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydb',
            name='photo',
        ),
        migrations.AddField(
            model_name='gallerydb',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopping.categorydb', verbose_name='К чему привязана картинка'),
        ),
        migrations.AlterField(
            model_name='reviewsdb',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_for_good', to='shopping.goodsdb', verbose_name='К какому товару привязан отзыв'),
        ),
    ]
