# Generated by Django 4.0.3 on 2022-04-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_remove_categorydb_photo_gallerydb_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsdb',
            name='photos',
        ),
        migrations.AddField(
            model_name='categorydb',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='gallerydb',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_for_goods', to='shopping.goodsdb', verbose_name='Картинка привязана к товару'),
        ),
    ]
